packages/editor/src/layouts/sidebar/LayerPanel.vue
packages/editor/src/layouts/workspace/Stage.vue
packages/editor/src/layouts/workspace/Workspace.vue
packages/editor/src/services/editor.ts
packages/editor/src/theme/common/var.scss
packages/editor/src/theme/layer-panel.scss
packages/editor/src/type.ts
packages/stage/src/StageCore.ts
packages/stage/src/StageHighlight.ts
packages/stage/src/StageMask.ts
packages/stage/src/types.ts

feat: 编辑器支持鼠标悬停高亮组件

---

packages/editor/src/layouts/sidebar/LayerPanel.vue
packages/editor/src/layouts/workspace/Stage.vue
packages/editor/src/layouts/workspace/Workspace.vue
packages/editor/src/services/editor.ts
packages/editor/src/theme/common/var.scss
packages/editor/src/theme/layer-panel.scss
packages/editor/src/type.ts
packages/stage/src/StageCore.ts
packages/stage/src/StageHighlight.ts
packages/stage/src/StageMask.ts
packages/stage/src/types.ts

编辑器支持鼠标悬停高亮组件

---

packages/stage/src/StageCore.ts
packages/stage/src/StageHighlight.ts
packages/stage/src/StageMask.ts

fix: 修复页面滚动高亮偏移的问题

---

packages/stage/src/StageCore.ts

修复了鼠标悬停高亮的一些问题

---

lerna.json

fix: 修复node版本16安装依赖失败的问题

---

package-lock.json
packages/stage/src/StageDragResize.ts
packages/stage/src/StageHighlight.ts
packages/stage/src/TargetCalibrate.ts
packages/stage/src/const.ts
packages/stage/src/types.ts
packages/ui-vue2/package-lock.json
runtime/vue2/package-lock.json

抽离出一个TargetCalibrate来校准元素定位，这块后续可能还会修改
目前可以解决弹窗场景下，以及固定定位下鼠标高亮偏移的问题

fix(highlight): 修复固定定位和弹窗场景下鼠标高亮偏移的问题

---

packages/stage/src/TargetCalibrate.ts

fix: 删除无用的方法

---

packages/stage/src/StageCore.ts
packages/stage/src/StageMask.ts

Reverts Tencent/tmagic-editor#53

Revert "feat(editor): 选中组件后自动滚动到组件位置"

---

package.json
playground/.env.react
playground/.env.vue2
playground/.env.vue3
playground/package.json
playground/src/pages/Editor.vue
runtime/react/package.json
runtime/react/src/playground/main.tsx
runtime/vue2/package.json
runtime/vue2/src/playground/App.vue
runtime/vue2/src/playground/main.ts
runtime/vue2/vite.config.ts

vue2 react runtime path 出错导致vue2 react playground运行出错；vue2中存在多个composition-api导致出错
fix #82 fix #68

feat: 支持playground:vue2/playground:react命令

---

packages/editor/src/services/editor.ts
packages/stage/package.json
packages/stage/src/StageCore.ts
packages/stage/src/StageDragResize.ts
packages/stage/src/StageMask.ts
packages/stage/src/StageMultiDragResize.ts
packages/stage/src/const.ts
packages/stage/src/types.ts
packages/stage/src/util.ts
pnpm-lock.yaml

支持通过按住shift键进行组件多选的能力

---

packages/editor/src/theme/framework.scss
packages/editor/src/theme/stage.scss

fix(editor): 修正css sass变量

---

packages/stage/src/style.css

不松开鼠标拖动, 从大容器到内部小容器拖拽, 不会改变父容器的问题,
修改前:
修改后:

fix(stage): 在 stage 拖拽改变父容器的BUG

---

packages/stage/src/StageRender.ts
packages/ui-react/src/useApp.ts
runtime/react/src/playground/App.css
runtime/vue2/src/playground/App.vue
runtime/vue3/src/playground/App.vue

fix(stage,runtime,ui-react): tmagicRuntimeReady时机修改

---

magic-admin/setup.sh
magic-admin/web/package.json
magic-admin/web/src/components/act-list.vue
magic-admin/web/src/config/blank-act-config.ts
magic-admin/web/src/use/use-publish.ts

fix(admin): npm install 出错

---

packages/editor/src/services/props.ts

fix: 修复copy粘贴相同类型组件，id被带入了新组件的问题
fix: 修改由于random产生重复id万分之一的概率提升至几百万分之一

fix: 修复copy粘贴相同类型组件，id被带入了新组件的问题

---

packages/editor/src/services/editor.ts
packages/editor/src/utils/operator.ts
packages/stage/src/StageCore.ts
packages/stage/src/StageMultiDragResize.ts
packages/stage/src/types.ts

1、多选粘贴后会选中粘贴的多个元素,并支持拖拽
2、粘贴删除撤销时，多个元素同时撤销
3、多选moveable使用单独的外部options参数，不与dr的混用避免互相影响

feat(editor): 多选粘贴后同步选中粘贴的多个元素,并支持拖拽,粘贴删除支持多个元素同时撤销到上一步

---

packages/editor/src/index.ts
packages/editor/src/layouts/workspace/ViewerMenu.vue
packages/editor/src/services/editor.ts
packages/editor/src/services/storage.ts
packages/editor/src/type.ts
packages/editor/tests/unit/services/editor.spec.ts

1、添加storageService服务，支持基础存储对象替换和方法拦截的形式进行拓展三方拓展
2、修改copy和paste原有localStorage为storageService
3、editor 支持导出 storageService

feat(editor): 添加storageService服务

---

packages/editor/src/services/editor.ts
packages/editor/src/services/storage.ts
packages/editor/tests/unit/services/editor.spec.ts

新增namespace，setItem/getItem时自动key自动加上namespace；setItem可以指定协议；getItem时根据协议自动解析
fix #224

feat(editor): 完善storageService功能

---

packages/editor/src/type.ts
packages/editor/src/utils/operator.ts

fix(editor): 添加组件粘贴操作支持偏移量

---

packages/stage/src/StageCore.ts
packages/stage/src/StageDragResize.ts
packages/stage/src/StageMultiDragResize.ts
packages/stage/src/types.ts

fix(stage): 修复多选组件处于拖拽状态时画布组件命中高亮的问题，优化多选拖拽体验

fix(stage): 修复多选组件处于拖拽状态时画布组件命中高亮的问题，优化多选拖拽体验

---

packages/stage/src/StageMultiDragResize.ts

fix(stage): 多选时禁止拖出边界

---

packages/editor/src/services/editor.ts

fix(editor): react runtime中添加没有即使渲染

---

packages/editor/src/services/editor.ts
packages/stage/src/types.ts
playground/src/pages/Editor.vue
runtime/vue2/playground/App.vue
runtime/vue3/playground/App.vue

fix(playground,runtime): 拖动添加弹窗时初始位置不对

---

packages/core/src/App.ts
packages/core/src/utils.ts

feat(core): 旋转角度支持配置不带单位的数值

---

packages/cli/src/utils/resolveAppPackages.ts

fix(cli): window下路径分隔符\转换为/

---

packages/editor/src/fields/UISelect.vue
packages/editor/src/layouts/sidebar/LayerPanel.vue

feat(editor): 记住组件树节点展开的状态

---

packages/ui-vue2/src/Component.vue
packages/ui-vue2/src/button/Button.vue
packages/ui-vue2/src/container/Container.vue
packages/ui-vue2/src/img/src/index.vue
packages/ui-vue2/src/overlay/src/index.vue
packages/ui-vue2/src/page/Page.vue
packages/ui-vue2/src/qrcode/src/index.vue
packages/ui-vue2/src/text/Text.vue
packages/ui/src/Component.vue
packages/ui/src/button/src/index.vue
packages/ui/src/container/src/Container.vue
packages/ui/src/img/src/index.vue
packages/ui/src/overlay/src/index.vue
packages/ui/src/page/src/index.vue
packages/ui/src/qrcode/src/index.vue
packages/ui/src/text/src/index.vue
runtime/vue2/page/main.ts
runtime/vue2/playground/main.ts
runtime/vue3/page/main.ts
runtime/vue3/playground/main.ts

fix(ui,runtime): 组件注册默认以magic-ui-xx的形式，不再需要在组件中设置name

---

packages/editor/src/services/editor.ts
packages/editor/src/type.ts

refactor(editor): 粘贴时添加粘贴选项，用于格式化粘贴对象数据。

---

packages/editor/src/services/editor.ts

1.修复 update 返回值三目运算符判断错误的问题，同时优化输入与输入类型一致。

fix(editor): 修复 update 返回值三目运算符判断错误的问题，同时优化输入与输入类型一致。

---

packages/editor/src/services/editor.ts
packages/editor/tests/unit/services/editor.spec.ts
packages/editor/tests/unit/utils/editor.spec.ts

fix(editor): 上移一层通知runtime更新参数出错

---

packages/editor/src/components/ScrollBar.vue
packages/editor/src/components/ScrollViewer.vue
packages/editor/src/layouts/workspace/Stage.vue
packages/editor/src/layouts/workspace/Workspace.vue
packages/editor/src/type.ts
packages/editor/src/utils/index.ts
packages/editor/src/utils/scroll-viewer.ts
packages/editor/src/utils/stage.ts

feat(editor): 画布添加滚动条

---

packages/stage/src/StageDragResize.ts

fix(stage): 流式布局resize从上或者左边调整，选中框出现错位

---

packages/editor/src/Editor.vue
packages/editor/src/layouts/PropsPanel.vue
packages/stage/src/StageDragResize.ts
packages/stage/src/style.css
packages/ui-react/src/container/Container.tsx
packages/ui-react/src/container/formConfig.ts
packages/ui-react/src/page/Page.tsx
packages/ui-react/src/page/formConfig.ts
packages/ui-vue2/src/container/Container.vue
packages/ui-vue2/src/container/formConfig.ts
packages/ui-vue2/src/container/initValue.ts
packages/ui-vue2/src/page/Page.vue
packages/ui-vue2/src/page/formConfig.ts
packages/ui/src/container/src/Container.vue
packages/ui/src/container/src/formConfig.ts
packages/ui/src/page/src/formConfig.ts
packages/ui/src/page/src/index.vue
runtime/vue2/playground/App.vue
runtime/vue3/playground/App.vue

fix(editor,stage,ui,runtime): 流式布局下，height自动设置成auto

---

packages/editor/src/services/editor.ts

fix(editor): 添加remove事件时的参数

---

packages/stage/src/StageMultiDragResize.ts

feat(stage): 多选支持resize

---

packages/core/src/App.ts

fix(core): 多个组件配置同一事件会导致此事件多次监听

---

packages/editor/src/Editor.vue
packages/editor/src/layouts/sidebar/Sidebar.vue
packages/editor/src/layouts/sidebar/TabPane.vue

feat(editor): 新增layer-node-content slot,用于定制组件树节点

---

packages/editor/src/index.ts

feat(editor): 导出CodeSelect组件

---

packages/core/src/App.ts
packages/core/src/Node.ts

chore(core): ts报错修改

---

packages/stage/src/StageDragResize.ts

fix(stage): 页面布局修改为流式布局后，组件宽可以设置到边框之外

---

packages/editor/src/layouts/sidebar/LayerPanel.vue

fix(editor): 设置高亮节点操作一定要在刷新展开状态之后，否则可能导致设置的高亮无效

---

packages/editor/src/layouts/workspace/Breadcrumb.vue
packages/editor/src/layouts/workspace/Workspace.vue
packages/editor/src/theme/breadcrumb.scss
packages/editor/src/theme/theme.scss
packages/editor/src/utils/stage.ts
packages/stage/src/MoveableSelectParentAble.ts
packages/stage/src/StageCore.ts
packages/stage/src/StageDragResize.ts
packages/stage/src/StageMask.ts
packages/stage/src/util.ts

feat(editor,stage): 在画布中支持选择父组件

---

README.md

chore: 更新Readme
